chore: testing history checks (#4)
* chore: testing history checks

* fix: adjusting linter to check history

* fix: adjusting linter to check history

* fix: adjusting linter to check history

* fix: adjusting linter to check history

* fix: adjusting linter to check history

* fix: adjusting linter to check history

* fix: got the conditions to resolve correctly

* fix: adjusting error message

* fix: adjusting error message

diff --git a/.github/workflows/migration-linter.yml b/.github/workflows/migration-linter.yml
--- a/.github/workflows/migration-linter.yml
+++ b/.github/workflows/migration-linter.yml
@@ -13,14 +13,25 @@ jobs:
       - uses: actions/checkout@v2
       - name: update checkout
         run: git fetch --prune
-      - name: migration-validation
-        run: bin/migration-validation.sh -b ${{ github.event.pull_request.base.ref }}
         shell: bash
       - name: Find modified migrations
         run: |
           modified_migrations=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF 'services/migration/src/**/*.sql')
           echo "$modified_migrations"
           echo "::set-output name=file_names::$modified_migrations"
+          
+          for i in "${modified_migrations[@]}"; do
+            # or do whatever with individual element of the array
+            does_file_exist=$(git cat-file -e origin/main:${i})
+
+            echo "${does_file_exist}"
+            if [[ -v "${does_file_exist}" ]]; then
+              echo "Error: this pr touches ${i}, which is a file already in history"
+              exit 1;
+            fi
+            
+          done
+
         id: modified-migrations
       - uses: sbdchd/squawk-action@v1
         with:
